import '../../api/models/firebase_models.dart';
import '../../api/models/youtube_models.dart';

/// Data dummy untuk development dan testing
class DummyData {
  /// Dummy Learning Materials
  static final List<LearningMaterialModel> learningMaterials = [
    LearningMaterialModel(
      id: 'material_1',
      title: 'Introduction to Flutter & Dart',
      description: 'Learn the basics of Flutter framework and Dart programming language. Perfect for beginners who want to start mobile app development.',
      category: 'Programming',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=1ukSR1GRtMU',
      thumbnailUrl: 'https://i.ytimg.com/vi/1ukSR1GRtMU/maxresdefault.jpg',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      tags: ['flutter', 'dart', 'mobile', 'programming'],
      difficulty: 1,
      estimatedDuration: 45,
      metadata: {
        'viewCount': 125000,
        'likeCount': 8500,
      },
    ),
    LearningMaterialModel(
      id: 'material_2',
      title: 'Advanced State Management with Riverpod',
      description: 'Deep dive into Riverpod state management. Learn best practices and advanced patterns for building scalable Flutter apps.',
      category: 'Programming',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example2',
      thumbnailUrl: 'https://picsum.photos/seed/riverpod/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      tags: ['flutter', 'riverpod', 'state-management', 'advanced'],
      difficulty: 4,
      estimatedDuration: 90,
      metadata: {
        'viewCount': 85000,
        'likeCount': 6200,
      },
    ),
    LearningMaterialModel(
      id: 'material_3',
      title: 'Calculus Made Easy: Derivatives',
      description: 'Understanding derivatives with practical examples. Perfect for students learning calculus for the first time.',
      category: 'Mathematics',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example3',
      thumbnailUrl: 'https://picsum.photos/seed/calculus/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      tags: ['mathematics', 'calculus', 'derivatives', 'tutorial'],
      difficulty: 2,
      estimatedDuration: 60,
      metadata: {
        'viewCount': 45000,
        'likeCount': 3800,
      },
    ),
    LearningMaterialModel(
      id: 'material_4',
      title: 'Introduction to Quantum Physics',
      description: 'Explore the fascinating world of quantum mechanics. Understanding wave-particle duality and quantum superposition.',
      category: 'Science',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example4',
      thumbnailUrl: 'https://picsum.photos/seed/quantum/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      tags: ['physics', 'quantum', 'science', 'advanced'],
      difficulty: 5,
      estimatedDuration: 120,
      metadata: {
        'viewCount': 95000,
        'likeCount': 7500,
      },
    ),
    LearningMaterialModel(
      id: 'material_5',
      title: 'Web Design Fundamentals',
      description: 'Learn the principles of great web design. Color theory, typography, and layout best practices.',
      category: 'Arts',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example5',
      thumbnailUrl: 'https://picsum.photos/seed/webdesign/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      tags: ['design', 'web', 'ui', 'ux'],
      difficulty: 2,
      estimatedDuration: 75,
      metadata: {
        'viewCount': 62000,
        'likeCount': 4900,
      },
    ),
    LearningMaterialModel(
      id: 'material_6',
      title: 'English Grammar: Advanced Tenses',
      description: 'Master complex English tenses. Perfect continuous, future perfect, and more with practical examples.',
      category: 'Languages',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example6',
      thumbnailUrl: 'https://picsum.photos/seed/english/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      tags: ['english', 'grammar', 'language', 'intermediate'],
      difficulty: 3,
      estimatedDuration: 50,
      metadata: {
        'viewCount': 38000,
        'likeCount': 2900,
      },
    ),
    LearningMaterialModel(
      id: 'material_7',
      title: 'Machine Learning for Beginners',
      description: 'Start your ML journey! Learn about supervised learning, neural networks, and practical applications.',
      category: 'Programming',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example7',
      thumbnailUrl: 'https://picsum.photos/seed/ml/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      tags: ['ai', 'machine-learning', 'python', 'beginner'],
      difficulty: 3,
      estimatedDuration: 100,
      metadata: {
        'viewCount': 156000,
        'likeCount': 12000,
      },
    ),
    LearningMaterialModel(
      id: 'material_8',
      title: 'JavaScript ES6+ Features',
      description: 'Modern JavaScript features: arrow functions, async/await, destructuring, and more.',
      category: 'Programming',
      type: 'youtube_video',
      url: 'https://www.youtube.com/watch?v=example8',
      thumbnailUrl: 'https://picsum.photos/seed/js/400/300',
      creatorId: 'demo_user',
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      tags: ['javascript', 'es6', 'web', 'programming'],
      difficulty: 2,
      estimatedDuration: 65,
      metadata: {
        'viewCount': 78000,
        'likeCount': 5600,
      },
    ),
  ];

  /// Dummy Study Groups
  static final List<StudyGroupModel> studyGroups = [
    StudyGroupModel(
      id: 'group_1',
      name: 'Flutter Developers Indonesia',
      description: 'Community untuk Flutter developers di Indonesia. Mari belajar dan berkembang bersama!',
      category: 'Programming',
      creatorId: 'demo_user',
      members: List.generate(42, (i) => 'user_$i'),
      maxMembers: 50,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      isPublic: true,
      imageUrl: 'https://picsum.photos/seed/flutter/200/200',
    ),
    StudyGroupModel(
      id: 'group_2',
      name: 'Calculus Study Group',
      description: 'Belajar kalkulus bareng-bareng. Diskusi soal, tips, dan trik menyelesaikan problem.',
      category: 'Mathematics',
      creatorId: 'demo_user',
      members: List.generate(28, (i) => 'user_${i + 50}'),
      maxMembers: 50,
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      isPublic: true,
      imageUrl: 'https://picsum.photos/seed/math/200/200',
    ),
    StudyGroupModel(
      id: 'group_3',
      name: 'Web Design Enthusiasts',
      description: 'Komunitas pecinta desain web. Share portfolio, feedback, dan inspirasi.',
      category: 'Arts',
      creatorId: 'demo_user',
      members: List.generate(35, (i) => 'user_${i + 100}'),
      maxMembers: 50,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
      isPublic: true,
      imageUrl: 'https://picsum.photos/seed/design/200/200',
    ),
    StudyGroupModel(
      id: 'group_4',
      name: 'Physics Lab',
      description: 'Grup untuk diskusi fisika, dari mekanika klasik sampai quantum physics.',
      category: 'Science',
      creatorId: 'demo_user',
      members: List.generate(19, (i) => 'user_${i + 150}'),
      maxMembers: 50,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
      isPublic: true,
      imageUrl: 'https://picsum.photos/seed/physics/200/200',
    ),
    StudyGroupModel(
      id: 'group_5',
      name: 'English Conversation Club',
      description: 'Practice your English speaking skills with friendly members from around the world.',
      category: 'Languages',
      creatorId: 'demo_user',
      members: List.generate(45, (i) => 'user_${i + 200}'),
      maxMembers: 50,
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
      isPublic: true,
      imageUrl: 'https://picsum.photos/seed/english/200/200',
    ),
    StudyGroupModel(
      id: 'group_6',
      name: 'Data Science Bootcamp',
      description: 'Intensive learning group for data science. Python, pandas, ML, and more.',
      category: 'Programming',
      creatorId: 'demo_user',
      members: List.generate(38, (i) => 'user_${i + 250}'),
      maxMembers: 50,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
      isPublic: true,
      imageUrl: 'https://picsum.photos/seed/datascience/200/200',
    ),
  ];

  /// Dummy YouTube Videos
  static final List<YouTubeVideo> youtubeVideos = [
    YouTubeVideo(
      id: 'video_1',
      title: 'Flutter Tutorial for Beginners',
      description: 'Complete Flutter course for absolute beginners. Build beautiful apps!',
      thumbnailUrl: 'https://picsum.photos/seed/vid1/400/300',
      channelTitle: 'Code Academy',
      channelId: 'channel_1',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      duration: 'PT45M30S',
      viewCount: 250000,
      likeCount: 18000,
      commentCount: 1200,
    ),
    YouTubeVideo(
      id: 'video_2',
      title: 'Advanced React Patterns',
      description: 'Learn advanced React patterns and best practices for production apps.',
      thumbnailUrl: 'https://picsum.photos/seed/vid2/400/300',
      channelTitle: 'Dev Masters',
      channelId: 'channel_2',
      publishedAt: DateTime.now().subtract(const Duration(days: 5)),
      duration: 'PT1H15M20S',
      viewCount: 180000,
      likeCount: 14500,
      commentCount: 890,
    ),
    YouTubeVideo(
      id: 'video_3',
      title: 'Python for Data Science',
      description: 'Master Python for data analysis, visualization, and machine learning.',
      thumbnailUrl: 'https://picsum.photos/seed/vid3/400/300',
      channelTitle: 'Data Science Pro',
      channelId: 'channel_3',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      duration: 'PT2H5M10S',
      viewCount: 420000,
      likeCount: 32000,
      commentCount: 2100,
    ),
    YouTubeVideo(
      id: 'video_4',
      title: 'UI/UX Design Principles',
      description: 'Essential design principles every developer should know.',
      thumbnailUrl: 'https://picsum.photos/seed/vid4/400/300',
      channelTitle: 'Design School',
      channelId: 'channel_4',
      publishedAt: DateTime.now().subtract(const Duration(days: 3)),
      duration: 'PT35M45S',
      viewCount: 95000,
      likeCount: 7200,
      commentCount: 450,
    ),
    YouTubeVideo(
      id: 'video_5',
      title: 'JavaScript Async Programming',
      description: 'Promises, async/await, and handling asynchronous operations in JS.',
      thumbnailUrl: 'https://picsum.photos/seed/vid5/400/300',
      channelTitle: 'JS Weekly',
      channelId: 'channel_5',
      publishedAt: DateTime.now().subtract(const Duration(hours: 18)),
      duration: 'PT28M15S',
      viewCount: 68000,
      likeCount: 5400,
      commentCount: 320,
    ),
    YouTubeVideo(
      id: 'video_6',
      title: 'Docker for Developers',
      description: 'Containerize your applications with Docker. Complete guide.',
      thumbnailUrl: 'https://picsum.photos/seed/vid6/400/300',
      channelTitle: 'DevOps Hub',
      channelId: 'channel_6',
      publishedAt: DateTime.now().subtract(const Duration(days: 4)),
      duration: 'PT52M30S',
      viewCount: 145000,
      likeCount: 11000,
      commentCount: 780,
    ),
    YouTubeVideo(
      id: 'video_7',
      title: 'Git & GitHub Crash Course',
      description: 'Version control essentials for modern developers.',
      thumbnailUrl: 'https://picsum.photos/seed/vid7/400/300',
      channelTitle: 'Code Academy',
      channelId: 'channel_1',
      publishedAt: DateTime.now().subtract(const Duration(days: 7)),
      duration: 'PT40M20S',
      viewCount: 320000,
      likeCount: 24000,
      commentCount: 1500,
    ),
    YouTubeVideo(
      id: 'video_8',
      title: 'SQL Database Design',
      description: 'Learn to design efficient and scalable database schemas.',
      thumbnailUrl: 'https://picsum.photos/seed/vid8/400/300',
      channelTitle: 'Database Pro',
      channelId: 'channel_7',
      publishedAt: DateTime.now().subtract(const Duration(days: 6)),
      duration: 'PT1H8M45S',
      viewCount: 112000,
      likeCount: 8900,
      commentCount: 620,
    ),
  ];

  /// Dummy User Stats
  static final Map<String, int> userStats = {
    'totalMaterials': 24,
    'completed': 8,
    'inProgress': 5,
    'studyGroups': 3,
  };
}
