// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFHNbZOz-VGr8FbtWMgJvAh97wuJs49w',
    appId: '1:1018894742415:web:228f5c43b2cc09319c51fa',
    messagingSenderId: '1018894742415',
    projectId: 'belajarbarengflutterproject',
    authDomain: 'belajarbarengflutterproject.firebaseapp.com',
    databaseURL: 'https://belajarbarengflutterproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbarengflutterproject.firebasestorage.app',
    measurementId: 'G-QNNW4PGZPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10KRHKDAXSQaKfMk54R_ZFNNggC8CzyM',
    appId: '1:1018894742415:android:499c550db37b63769c51fa',
    messagingSenderId: '1018894742415',
    projectId: 'belajarbarengflutterproject',
    databaseURL: 'https://belajarbarengflutterproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbarengflutterproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUnhWrn1lpR9EC6GlNonBt0loIVKjxBc',
    appId: '1:1018894742415:ios:6c525b998e8915d59c51fa',
    messagingSenderId: '1018894742415',
    projectId: 'belajarbarengflutterproject',
    databaseURL: 'https://belajarbarengflutterproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbarengflutterproject.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUnhWrn1lpR9EC6GlNonBt0loIVKjxBc',
    appId: '1:1018894742415:ios:6c525b998e8915d59c51fa',
    messagingSenderId: '1018894742415',
    projectId: 'belajarbarengflutterproject',
    databaseURL: 'https://belajarbarengflutterproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbarengflutterproject.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATFHNbZOz-VGr8FbtWMgJvAh97wuJs49w',
    appId: '1:1018894742415:web:27ca854f696ed4ef9c51fa',
    messagingSenderId: '1018894742415',
    projectId: 'belajarbarengflutterproject',
    authDomain: 'belajarbarengflutterproject.firebaseapp.com',
    databaseURL: 'https://belajarbarengflutterproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajarbarengflutterproject.firebasestorage.app',
    measurementId: 'G-F599MKWNWX',
  );
}
